package org.bandex;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.sax.SAXResult;
import javax.xml.transform.stream.StreamSource;

import org.apache.fop.apps.FOUserAgent;
import org.apache.fop.apps.Fop;
import org.apache.fop.apps.FopFactory;
import org.apache.fop.apps.MimeConstants;

/**
 * A servlet corresponding to the PDF version of the menu.
 */
@WebServlet("/cardapio.pdf")
public class PdfServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public PdfServlet() {
		super();
	}

	/**
	 * Generates and sends the PDF file to the user.
	 * 
	 * @param out
	 *            The OutputStream generated by the "response" variable of
	 *            method "doGet()".
	 * @param all
	 *            True if the whole menu should be displayed; false if only the
	 *            dessert is to be shown.
	 */
	protected void toPDF(OutputStream out, boolean all) {
		try {
			URL xmlfile = new URL("http://www.pcasc.usp.br/restaurante.xml");

			String xsltfile;
			if (all)
				xsltfile = "/restaurante-fo-tudo.xsl";
			else
				xsltfile = "/restaurante-fo-sobremesa.xsl";

			ServletContext context = getServletContext();

			InputStream is = context.getResourceAsStream(xsltfile);

			StreamSource XSLTSource = new StreamSource(is);

			FopFactory fopFactory = FopFactory.newInstance();

			FOUserAgent foUserAgent = fopFactory.newFOUserAgent();

			try {
				Fop fop = fopFactory.newFop(MimeConstants.MIME_PDF,
						foUserAgent, out);

				TransformerFactory factory = TransformerFactory.newInstance();
				Transformer transformer = factory.newTransformer(XSLTSource);

				transformer.setParameter("versionParam", "2.0");

				Source src = new StreamSource(xmlfile.openStream());

				Result res = new SAXResult(fop.getDefaultHandler());

				transformer.transform(src, res);
			} finally {
				out.close();
			}
		} catch (Exception e) {
			e.printStackTrace(System.err);
		}
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		OutputStream out = response.getOutputStream();
		String all = request.getParameter("all");
		if (all == null)
			toPDF(out, true);
		else if (all.compareTo("true") == 0)
			toPDF(out, true);
		else
			toPDF(out, false);
		out.close();
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

}
